/* Generated by scripts/build-cloud.cjs; never cache API responses or user uploads. */
const CACHE = 'knowledge-pwa-54bf5ea413ed98b7';
const FILES = ["/assets/css/app.css","/assets/css/cloud.css","/assets/css/library.css","/assets/data/library.js","/assets/icons/app-192.png","/assets/icons/app-512.png","/assets/js/backup-model.js","/assets/js/backup.js","/assets/js/bootstrap.js","/assets/js/cloud-config.js","/assets/js/cloud-model.js","/assets/js/cloud-sync.js","/assets/js/diagrams.js","/assets/js/extract-exports.js","/assets/js/extract-generation.js","/assets/js/extract-parsers.js","/assets/js/extract-storage.js","/assets/js/extraction.js","/assets/js/knowledge-dialog.js","/assets/js/knowledge-storage.js","/assets/js/library-manager.js","/assets/js/library-model.js","/assets/js/library-preferences.js","/assets/js/library.js","/assets/js/navigation.js","/assets/js/pwa.js","/assets/js/question-model.js","/assets/js/review-engine.js","/assets/js/review-ui.js","/assets/js/search.js","/assets/js/sync.js","/assets/vendor/supabase.js","/index.html","/manifest.webmanifest","/嵌入式校招八股_总览.html"];
self.addEventListener('install', event => { event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(FILES))); });
self.addEventListener('message', event => { if (event.data === 'activate') self.skipWaiting(); });
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key.startsWith('knowledge-pwa-') && key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || url.origin !== self.location.origin || url.pathname.startsWith('/api/')) return;
  const path = decodeURI(url.pathname);
  if (event.request.mode === 'navigate' && ['/', '/index.html', '/嵌入式校招八股_总览.html'].includes(path)) {
    event.respondWith(caches.open(CACHE).then(cache => cache.match('/index.html').then(cached => cached || fetch(event.request)))); return;
  }
  if (!FILES.includes(path)) return;
  event.respondWith(caches.open(CACHE).then(cache => cache.match(path).then(cached => cached || fetch(event.request))));
});
